# Netlify configuration for Top 100 Hall of Fame

[build]
  # Since we're using a simple HTML site, no build process needed
  publish = "."
  command = ""

# Security headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000"

# Cache static assets longer
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Friendly URL redirects
[[redirects]]
  from = "/halloffame"
  to = "/"
  status = 301

[[redirects]]
  from = "/hof"
  to = "/"
  status = 301

[[redirects]]
  from = "/hall-of-fame"
  to = "/"
  status = 301

[[redirects]]
  from = "/legends"
  to = "/"
  status = 301

# 404 page handling (optional - you can create a custom 404.html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Environment variables (if you need them later)
# [build.environment]
#   NODE_VERSION = "18"

# Plugin configuration (for future enhancements)
# [[plugins]]
#   package = "@netlify/plugin-sitemap"

# Forms configuration (if you add contact forms later)
# [build.processing]
#   skip_processing = false
# [build.processing.css]
#   bundle = true
#   minify = true
# [build.processing.js]
#   bundle = true
#   minify = true
